{{- if .Values.integrationManagerBase.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "integration-manager.base.fullname" . }}
  labels:
    app: integration-manager
    component: base
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: integration-manager
      component: base
      release: {{ .Release.Name }}
  {{ toYaml .Values.integrationManagerBase.pdb | indent 2 | trim }}
{{- end }}
