{{- if .Values.staticContent.pdb }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "integration-manager.static-content.fullname" . }}
  labels:
    app: integration-manager
    component: static-content
    chart: {{ template "integration-manager.chart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: integration-manager
      component: static-content
      release: {{ .Release.Name }}
  {{ toYaml .Values.staticContent.pdb | indent 2 | trim }}
{{- end }}
